[package]
name = "ray_rs"
version = "0.1.0"
authors = ["litianqi <litianqi@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vek = "0.12.1"
roots = "0.0.6"
image = "0.23.12"
rayon = "1.5.0"
